[http.middlewares.simpleAuth.basicAuth]
  users = [
    "$htpasswdoutput"
  ]

[http.routers.api]
  rule = "Host(`$DOMAIN_FOR_TRAEFIK`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"

  [tls.options.mintls13]
    minVersion = "VersionTLS13"

